project_id: environment-data
topic_id: datalogger
dataset_id: lisbon-arroz
device_id: RaspberryZeroW-0001
enabled_sensors: ['SPECTRUM', 'HUM_TEMP', 'HUM_TEMP_PRES']
measurement_cycle_length: 3 # measurements interval
submit_after_cycles: 20 # submission interval (number of data points) of data -> mean is calculated for this interval
